# Generated by Django 4.0 on 2021-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
